### ISSUE TITLE
Register template to the PAM50 space

### ISSUE THREAD

**Issue by charleygros** [sct-pipeline/exvivo-template#1]
Task: Register the exvivo MRI template to the PAM50 space.

Challenge: We only have the spinal level labelling, C2 to C8, ie no vertebral level information.

`PAM50/spinal_levels/spinal_levels_*.nii.gz` are available with a probabilistic distribution for each level.

**Comment by charleygros** [comment]
### Naive option:
- For each `PAM50/spinal_levels/spinal_levels_*.nii.gz`, compute the center of mass of the distribution and assign a label (one voxel) associated to this level.
- Use the above labels to generate a single Nifti file containing one label per level. Note: this is different of `PAM50/template/PAM50_levels.nii.gz`, which has the entire body labelled (vs here one point). But I think it will be okay since `sct_label_utils -vert-body` is applied to this file at some point in `sct_register_to_template` ([here](`PAM50/template/PAM50_levels.nii.gz`)).
- Use this file instead of `PAM50/template/PAM50_levels.nii.gz` inside `sct_register_to_template`.

**Comment by jcohenadad** [comment]
Great suggestions @charleygros! Since the spinal level-based registration could be used in the future for other projects, i suggest we integrate that feature in SCT as of now. I've created an issue [here](https://github.com/neuropoly/spinalcordtoolbox/issues/2509).
