### ISSUE TITLE
Template validation

### ISSUE THREAD

**Issue by charleygros** [sct-pipeline/exvivo-template#3]
We need to develop methods to validation the new exvivo template:

1. **Template creation accuracy**: compute the mean and maximum distance error between each individual spinal cord centerline and the template centerline, after registration to the
template.

2. **GM mask creation accuracy**: compute the Dice score and Hausdorff distance between each individual GM mask and the template GM probabilistic mask, after registration to the
template.

3. **Accuracy of the registration between the PAM50 and the exvivo template**: Dice score for SC and GM masks across the common IS coverage.

What do you think @jcohenadad & @nyoman1994 ?

**Comment by jcohenadad** [comment]
@charleygros these are excellent suggestions. For point 2 we should probably threshold the template mask (at 0.5) to be able to compute a Dice score.

for the registration to the PAM50, i am wondering how we should proceed in terms of final resolution. Obviously we don't want to sub-sample the exvivo template (it would defeat the purpose). So, should we first upsample the PAM50 to the resolution of the exvivo template, and then register the exvivo template to the PAM50 (that way, the q/sform of the registered exvivo template would match that of the PAM50, regardless the resolution). Maybe we should move this discussion somewhere else...
